- hosts: home-assistant
  # become: true
  tasks:

  - name: copy HA config
    synchronize:
      src: home-assistant/
      dest: /root/config/
      
  - name: copy app-daemon config
    synchronize:
      src: app-daemon/
      dest: /root/config/appdaemon/


# restart?
# hassio homeassistant restart