homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 43
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

  auth_providers:
   - type: homeassistant

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
weather:
  - platform: met

wake_on_lan:

sensor:
  - platform: rpi_power
    text_state: true

  - platform: miflora
    mac: !secret mac_miflora
device_tracker:
  - platform: google_maps
    username: !secret google_maps_username
    password: !secret google_maps_password



# Text to speech
tts:
  - platform: google_translate


tradfri:
  host: 192.168.1.127


recorder:
  purge_keep_days: 7
  purge_interval: 1
  exclude:
    domains:
      - sun
      - media_player
      - updater

    entities:
      - sensor.o2_homebox_2_6741_packets_sec_sent
      - sensor.o2_homebox_2_6741_packets_sec_received
      - sensor.o2_homebox_2_6741_bytes_sent
      - sensor.o2_homebox_2_6741_packets_sent
      - sensor.o2_homebox_2_6741_bytes_received
      - sensor.o2_homebox_2_6741_packets_received



zha:
 usb_path: /dev/ttyAMA0
 database_path: zigbee.db
 baudrate: 57600


input_select:
  light_mode_livingroom:
    name: Light Mode
    options:
      - "auto"
      - "manual"
    icon: mdi:target

  light_mode_bedroom:
    name: Light Mode
    options:
      - "auto"
      - "manual"
    icon: mdi:target

  light_mode_bathroom:
    name: Light Mode
    options:
      - "auto"
      - "manual"
    icon: mdi:target

logger:
  default: info
#   logs:
#    homeassistant.components.zha: debug
#    bellows.ezsp: debug
#    bellows.uart: debug
#    zigpy.zdo: debug
#    zigpy.application: debug


lovelace:

system_health:

cloud: !include cloud.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include light_groups.yaml
scene: !include scene.yaml