# raspberry LEDs
- platform: raspberry_led

# living room
- platform: group
  name: Livingroom spots main
  entities:
    - light.lc_0
    - light.lc_1
    - light.lc_2
    - light.lc_3
    - light.lc_4
    - light.lc_5

- platform: group
  name: Livingroom spots beam
  entities:
    - light.beam_1
    - light.beam_2
    - light.beam_3

- platform: group
  name: Livingroom RGB lights
  entities:
    - light.l_rgb_0
    - light.l_rgb_1
    - light.l_rgb_2


# bathroom
- platform: group
  name: Bathroom lights
  entities:
    - light.t1
    - light.t2
    - light.t3
    - light.t4
    - light.t5
    - light.t6
    - light.t7
    - light.t8

# bedroom
- platform: group
  name: Bedroom lights
  entities:
    - light.b1
    - light.b2
    - light.b3
    - light.b4


- platform: group
  name: Hallway lights
  entities:
    - light.h1
    - light.h2
    - light.h3
    - light.h4
    - light.h5
    - light.h6
    - light.h7
    - light.h8


- platform: group
  name: Kitchen lights
  entities:
    - light.kitchen_counter
    - light.shelly1_0