resources:
  - type: js
    url: /local/monster-card-b50aedba9f0e1627848a6c3d809bc4f6439b3857.js
  - type: js
    url: /local/floorplan-helper.js
title: Home
views:
  - badges:
      - sensor.yr_symbol
      - sensor.bedroom
      - sensor.wohnzimmer_unten
      - sensor.wohnzimmer_decke
      - sun.sun
    cards:
      - entities:
          - automation.automation_0
          - automation.automation_1
        title: Automatisierung
        type: entities
      - entity: media_player.bedroom_speaker
        type: media-control
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.bathroom_speaker
        type: media-control
      - entity: media_player.all_devices_3
        type: media-control
      - entities:
          - script.shutdown
        title: Skript
        type: entities
      - type: weather-forecast
        entity: weather.met_no
        name: Weather
    icon: 'mdi:home-circle'
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - entity: group.livingroom_rgb_lights
          - entity: group.livingroom_spots
          - entity: input_select.light_mode_livingroom
        type: entities
      - entity: media_player.living_room_speaker
        type: media-control
      - entities:
          - entity: sensor.mi_flora_battery
          - entity: sensor.mi_flora_conductivity
          - entity: sensor.mi_flora_light_intensity
          - entity: sensor.mi_flora_moisture
          - entity: sensor.mi_flora_temperature
        type: glance
    icon: 'mdi:cat'
    theme: default
    title: Livingroom
  - badges: []
    cards:
      - entities:
          - entity: group.bedroom_lights
        type: entities
      - entity: media_player.bedroom_speaker
        type: media-control
    icon: 'mdi:power-sleep'
    title: Bedroom
  - badges: []
    cards:
      - type: media-control
        entity: media_player.bathroom_speaker
    icon: 'mdi:swim'
    title: bathroom
  - badges: []
    cards:
      - elements:
          - entity: group.bedroom_lights
            style:
              left: 74%
              top: 72%
            tap_action:
              action: toggle
            type: state-icon
          - entity: group.livingroom_spots
            style:
              left: 45%
              top: 64%
            tap_action:
              action: toggle
            type: state-icon
          - entity: group.livingroom_rgb_lights
            style:
              left: 45%
              top: 83%
            tap_action:
              action: toggle
            type: state-icon
        image: /local/floorplan.png
        type: picture-elements
    icon: 'mdi:floor-plan'
    title: floor plan
    panel: true
